language: python
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: trusty
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - CC=gcc-4.9
         - CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      dist: trusty
      python: "2.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - CC=gcc-4.9
         - CXX=g++-4.9"

    - os: osx
      python: "3.6"
      osx_image: xcode8.3
# command to install dependencies
before_install:
    - eval "${MATRIX_EVAL}"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
# tests
script:
  - cd tests
  - python -m unittest discover -p '*.py'
